config/routes.rb
Rails.application.routes.draw do
  get 'player_search/show'
  post 'player_search/search'
  get 'select_item/show'
  post 'select_item/search'
  get 'result/show'
  get 'maker_search/show'
  post 'maker_search/search'
  resources :rackets
  resources :rankings
  resources :players
  resources :series
  resources :makers
  devise_for :users, :controllers => {
  :registrations => "registrations"
  }
  root 'static_pages#home'
end

app/models/ranking.rb
class Ranking < ApplicationRecord
    belongs_to :racket
    validates :ranking_year, presence: true
    validates :ranking_month, presence: true
    validates :ranking_week, presence: true
    validates :rank, presence: true
    validates :racket_id, presence: true
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  before_action :set_ranking, only: [:show, :edit, :update, :destroy]

  # GET /rankings
  # GET /rankings.json
  def index
    @rankings = Ranking.all
  end

  # GET /rankings/1
  # GET /rankings/1.json
  def show
  end

  # GET /rankings/new
  def new
    @ranking = Ranking.new
  end

  # GET /rankings/1/edit
  def edit
  end

  # POST /rankings
  # POST /rankings.json
  def create
    @ranking = Ranking.new(ranking_params)

    respond_to do |format|
      if @ranking.save
        format.html { redirect_to @ranking, notice: 'Ranking was successfully created.' }
        format.json { render :show, status: :created, location: @ranking }
      else
        format.html { render :new }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rankings/1
  # PATCH/PUT /rankings/1.json
  def update
    respond_to do |format|
      if @ranking.update(ranking_params)
        format.html { redirect_to @ranking, notice: 'Ranking was successfully updated.' }
        format.json { render :show, status: :ok, location: @ranking }
      else
        format.html { render :edit }
        format.json { render json: @ranking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rankings/1
  # DELETE /rankings/1.json
  def destroy
    @ranking.destroy
    respond_to do |format|
      format.html { redirect_to rankings_url, notice: 'Ranking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ranking
      @ranking = Ranking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ranking_params
      params.require(:ranking).permit(:ranking_year, :ranking_month, :ranking_week, :rank, :racket_id)
    end
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/rankings/_form.html.erb
<%= form_with(model: ranking, local: true) do |form| %>
  <% if ranking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ranking.errors.count, "error") %> prohibited this ranking from being saved:</h2>

      <ul>
      <% ranking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :年 %>
    <%= form.number_field :ranking_year, id: :ranking_ranking_year %>
  </div>

  <div class="field">
    <%= form.label :月 %>
    <%= form.number_field :ranking_month, id: :ranking_ranking_month %>
  </div>

  <div class="field">
    <%= form.label :週 %>
    <%= form.number_field :ranking_week, id: :ranking_ranking_week %>
  </div>

  <div class="field">
    <%= form.label :ランク %>
    <%= form.number_field :rank, id: :ranking_rank %>
  </div>

  <div class="field">
    <%= form.label :対象ラケットのid %>
    <%= form.number_field :racket_id, id: :ranking_racket_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rankings/edit.html.erb
<h1>Editing Ranking</h1>

<%= render 'form', ranking: @ranking %>

<%= link_to 'Show', @ranking %> |
<%= link_to 'Back', rankings_path %>

app/views/rankings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rankings</h1>

<table>
  <thead>
    <tr>
      <th>Ranking year</th>
      <th>Ranking month</th>
      <th>Ranking week</th>
      <th>Rank</th>
      <th>Racket</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rankings.each do |ranking| %>
      <tr>
        <td><%= ranking.ranking_year %></td>
        <td><%= ranking.ranking_month %></td>
        <td><%= ranking.ranking_week %></td>
        <td><%= ranking.rank %></td>
        <td><%= ranking.racket_id %></td>
        <td><%= link_to 'Show', ranking %></td>
        <td><%= link_to 'Edit', edit_ranking_path(ranking) %></td>
        <td><%= link_to 'Destroy', ranking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ranking', new_ranking_path %>

app/views/rankings/new.html.erb
<h1>New Ranking</h1>

<%= render 'form', ranking: @ranking %>

<%= link_to 'Back', rankings_path %>

app/views/rankings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ranking year:</strong>
  <%= @ranking.ranking_year %>
</p>

<p>
  <strong>Ranking month:</strong>
  <%= @ranking.ranking_month %>
</p>

<p>
  <strong>Ranking week:</strong>
  <%= @ranking.ranking_week %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @ranking.rank %>
</p>

<p>
  <strong>Racket:</strong>
  <%= @ranking.racket_id %>
</p>

<%= link_to 'Edit', edit_ranking_path(@ranking) %> |
<%= link_to 'Back', rankings_path %>