config/routes.rb
Rails.application.routes.draw do
  get 'player_search/show'
  post 'player_search/search'
  get 'select_item/show'
  post 'select_item/search'
  get 'result/show'
  get 'maker_search/show'
  post 'maker_search/search'
  resources :rackets
  resources :rankings
  resources :players
  resources :series
  resources :makers
  devise_for :users, :controllers => {
  :registrations => "registrations"
  }
  root 'static_pages#home'
end

app/models/racket.rb
class Racket < ApplicationRecord
  belongs_to :series
  has_many :players, dependent: :destroy
  has_many :rankings, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50}
  validates :maker_id, presence: true
  validates :series_id, presence: true
  validates :level, presence: true
  validates :point_physical, presence: true
  validates :point_playing_style, presence: true
  validates :point_support, presence: true
  validates :point_spin, presence: true
  validates :point_feeling, presence: true
  validates :spec_weight, presence: true
  validates :spec_face, presence: true
  validates :spec_thickness, presence: true
  validates :spec_balance, presence: true
  validates :spec_length, presence: true
  validates :spec_string_pattern, presence: true
  validates :spec_model, presence: true
  validates :url, presence: true, length: { maximum:500 }
  has_attached_file :image, styles: { medium: "200x150>", thumb: "50x50>" }
  validates_attachment_content_type :image, :content_type => %w(image/jpeg image/jpg image/png image/gif)
  validates :image, presence: true
end

app/controllers/rackets_controller.rb
class RacketsController < ApplicationController
  before_action :set_racket, only: [:show, :edit, :update, :destroy]

  # GET /rackets
  # GET /rackets.json
  def index
    @rackets = Racket.all
  end

  # GET /rackets/1
  # GET /rackets/1.json
  def show
  end

  # GET /rackets/new
  def new
    @racket = Racket.new
  end

  # GET /rackets/1/edit
  def edit
  end

  # POST /rackets
  # POST /rackets.json
  def create
    @racket = Racket.new(racket_params)

    respond_to do |format|
      if @racket.save
        format.html { redirect_to @racket, notice: 'Racket was successfully created.' }
        format.json { render :show, status: :created, location: @racket }
      else
        format.html { render :new }
        format.json { render json: @racket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rackets/1
  # PATCH/PUT /rackets/1.json
  def update
    respond_to do |format|
      if @racket.update(racket_params)
        format.html { redirect_to @racket, notice: 'Racket was successfully updated.' }
        format.json { render :show, status: :ok, location: @racket }
      else
        format.html { render :edit }
        format.json { render json: @racket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rackets/1
  # DELETE /rackets/1.json
  def destroy
    @racket.destroy
    respond_to do |format|
      format.html { redirect_to rackets_url, notice: 'Racket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_racket
      @racket = Racket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def racket_params
      params.require(:racket).permit(:name, :maker_id, :series_id, :model_player_id, :level, :point_physical, :point_playing_style, :point_support, :point_spin, :point_feeling, :spec_weight, :spec_face, :spec_thickness, :spec_balance, :spec_length, :spec_string_pattern, :spec_model, :url, :price, :page_count, :string_id, :image)
    end
end

app/helpers/rackets_helper.rb
module RacketsHelper
end

app/views/rackets/_form.html.erb
<%= form_with(model: racket, local: true) do |form| %>
  <% if racket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(racket.errors.count, "error") %> prohibited this racket from being saved:</h2>

      <ul>
      <% racket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :名前 %>
    <%= form.text_field :name, id: :racket_name %>
  </div>

  <div class="field">
    <%= form.label :メーカーのid %>
    <%= form.number_field :maker_id, id: :racket_maker_id %>
  </div>

  <div class="field">
    <%= form.label :シリーズのid %>
    <%= form.number_field :series_id, id: :racket_series_id %>
  </div>

  <div class="field">
    <%= form.label :代表選手のid %>
    <%= form.number_field :model_player_id, id: :racket_model_player_id %>
  </div>

  <div class="field">
    <%= form.label :対象レベル %>
    <%= form.number_field :level, id: :racket_level %>
  </div>

  <div class="field">
    <%= form.label :体力の評点 %>
    <%= form.number_field :point_physical, id: :racket_point_physical %>
  </div>

  <div class="field">
    <%= form.label :プレースタイルの評点 %>
    <%= form.number_field :point_playing_style, id: :racket_point_playing_style %>
  </div>

  <div class="field">
    <%= form.label :サポートの評点 %>
    <%= form.number_field :point_support, id: :racket_point_support %>
  </div>

  <div class="field">
    <%= form.label :スピンの評点 %>
    <%= form.number_field :point_spin, id: :racket_point_spin %>
  </div>

  <div class="field">
    <%= form.label :打感の評点 %>
    <%= form.number_field :point_feeling, id: :racket_point_feeling %>
  </div>

  <div class="field">
    <%= form.label :重量 %>
    <%= form.number_field :spec_weight, id: :racket_spec_weight %>
  </div>

  <div class="field">
    <%= form.label :面の大きさ %>
    <%= form.number_field :spec_face, id: :racket_spec_face %>
  </div>

  <div class="field">
    <%= form.label :厚さ %>
    <%= form.text_field :spec_thickness, id: :racket_spec_thickness %>
  </div>

  <div class="field">
    <%= form.label :バランス %>
    <%= form.number_field :spec_balance, id: :racket_spec_balance %>
  </div>

  <div class="field">
    <%= form.label :長さ %>
    <%= form.number_field :spec_length, id: :racket_spec_length %>
  </div>

  <div class="field">
    <%= form.label :ストリングパターン %>
    <%= form.text_field :spec_string_pattern, id: :racket_spec_string_pattern %>
  </div>

  <div class="field">
    <%= form.label :モデル %>
    <%= form.text_field :spec_model, id: :racket_spec_model %>
  </div>

  <div class="field">
    <%= form.label :販売url %>
    <%= form.text_field :url, id: :racket_url %>
  </div>

  <div class="field">
    <%= form.label :価格 %>
    <%= form.number_field :price, id: :racket_price %>
  </div>

  <div class="field">
    <%= form.label :ページ表示回数 %>
    <%= form.number_field :page_count, id: :racket_page_count %>
  </div>

  <div class="field">
    <%= form.label :おすすめガットのid %>
    <%= form.number_field :string_id, id: :racket_string_id %>
  </div>
  
  <div class="field">
    <%= form.label :写真 %>
    <%= form.file_field :image %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rackets/edit.html.erb
<h1>Editing Racket</h1>

<%= render 'form', racket: @racket %>

<%= link_to 'Show', @racket %> |
<%= link_to 'Back', rackets_path %>

app/views/rackets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rackets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Maker</th>
      <th>Series</th>
      <th>Model player</th>
      <th>Level</th>
      <th>Point physical</th>
      <th>Point playing style</th>
      <th>Point support</th>
      <th>Point spin</th>
      <th>Point feeling</th>
      <th>Spec weight</th>
      <th>Spec face</th>
      <th>Spec thickness</th>
      <th>Spec balance</th>
      <th>Spec length</th>
      <th>Spec string pattern</th>
      <th>Spec model</th>
      <th>Url</th>
      <th>Price</th>
      <th>Page count</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rackets.each do |racket| %>
      <tr>
        <td><%= racket.name %></td>
        <td><%= racket.maker_id %></td>
        <td><%= racket.series_id %></td>
        <td><%= racket.model_player_id %></td>
        <td><%= racket.level %></td>
        <td><%= racket.point_physical %></td>
        <td><%= racket.point_playing_style %></td>
        <td><%= racket.point_support %></td>
        <td><%= racket.point_spin %></td>
        <td><%= racket.point_feeling %></td>
        <td><%= racket.spec_weight %></td>
        <td><%= racket.spec_face %></td>
        <td><%= racket.spec_thickness %></td>
        <td><%= racket.spec_balance %></td>
        <td><%= racket.spec_length %></td>
        <td><%= racket.spec_string_pattern %></td>
        <td><%= racket.spec_model %></td>
        <td><%= racket.url %></td>
        <td><%= racket.price %></td>
        <td><%= racket.page_count %></td>
        <td><%= racket.string_id %></td>
        <td><%= link_to 'Show', racket %></td>
        <td><%= link_to 'Edit', edit_racket_path(racket) %></td>
        <td><%= link_to 'Destroy', racket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Racket', new_racket_path %>

app/views/rackets/new.html.erb
<h1>New Racket</h1>

<%= render 'form', racket: @racket %>

<%= link_to 'Back', rackets_path %>

app/views/rackets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @racket.name %>
</p>

<p>
  <strong>Maker:</strong>
  <%= @racket.maker_id %>
</p>

<p>
  <strong>Series:</strong>
  <%= @racket.series_id %>
</p>

<p>
  <strong>Model player:</strong>
  <%= @racket.model_player_id %>
</p>

<p>
  <strong>Level:</strong>
  <%= @racket.level %>
</p>

<p>
  <strong>Point physical:</strong>
  <%= @racket.point_physical %>
</p>

<p>
  <strong>Point playing style:</strong>
  <%= @racket.point_playing_style %>
</p>

<p>
  <strong>Point support:</strong>
  <%= @racket.point_support %>
</p>

<p>
  <strong>Point spin:</strong>
  <%= @racket.point_spin %>
</p>

<p>
  <strong>Point feeling:</strong>
  <%= @racket.point_feeling %>
</p>

<p>
  <strong>Spec weight:</strong>
  <%= @racket.spec_weight %>
</p>

<p>
  <strong>Spec face:</strong>
  <%= @racket.spec_face %>
</p>

<p>
  <strong>Spec thickness:</strong>
  <%= @racket.spec_thickness %>
</p>

<p>
  <strong>Spec balance:</strong>
  <%= @racket.spec_balance %>
</p>

<p>
  <strong>Spec length:</strong>
  <%= @racket.spec_length %>
</p>

<p>
  <strong>Spec string pattern:</strong>
  <%= @racket.spec_string_pattern %>
</p>

<p>
  <strong>Spec model:</strong>
  <%= @racket.spec_model %>
</p>

<p>
  <strong>Url:</strong>
  <%= @racket.url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @racket.price %>
</p>

<p>
  <strong>Page count:</strong>
  <%= @racket.page_count %>
</p>

<p>
  <strong>String:</strong>
  <%= @racket.string_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @racket.image.url(:medium) %>
</p>

<%= link_to 'Edit', edit_racket_path(@racket) %> |
<%= link_to 'Back', rackets_path %>